### PR TITLE
Add install of v2-as-default

### PR DESCRIPTION
**Pull request by cferenba**
This adds the `gftl-shared-v2-as-default` directory to the install list for gftl-shared.  This will be needed by an upcoming pFUnit change that switches that package to use the v2 interfaces.

### CODE REVIEW

**Comment by cferenba** [comment]
The CI failure has the message:
```
/home/runner/work/_temp/1652b1ca-3bb0-4904-be30-cf5d3802556f.sh: line 1: gfortran-13: command not found
```
which is not related to the change in this MR.

**Review by tclune — APPROVED** [review]
Hmm.  I'd have thought that there were more changes needed ...

Thanks!

**Comment by mathomp4** [comment]
> Yes - I'll ignore the gcc-13 issue. (Hopefully CI gets fixed in the near future.)

I think this is fixed in #75

**Comment by tclune** [comment]
Oops - I thought this was a PR on pFUnit.   Lots of other projects depend on gftl-shared, so I strongly suspect I need to revert this PR.

**Comment by tclune** [comment]
Will try to expedite such testing ...

**Comment by cferenba** [comment]
I don't think the PR needs to be reverted.  It does add a new install, but nobody will pick up the new directory unless they explicitly request it.

**Comment by cferenba** [comment]
And I should add, there's a larger set of changes coming in pFUnit for the v1-to-v2 transition, but they will not build without this change.

**Comment by tclune** [comment]
Ah - apologies for the noise.   Rushing around trying to take care of several issues after a day of meetings.

Instead, I guess I have a question then - how is this helping with the pFunit issue and the Cray compiler then?   Will there be a separate PR there to use the new install target?

**Comment by tclune** [comment]
Ah - just saw your other email.  I'm less confused now.

Cheers.

**Pull request merged**
